Projekt/config/routes.rb
Rails.application.routes.draw do

  resources :categories
  get 'galleries_gal' => 'galleries#gal'
  get 'categories_cat' => 'categories#cat'
  get 'galleries_new' => 'galleries#new'

  resources :galleries do
    resources :comments
  end
  devise_for :users

 root to: 'galleries#index'

end

Projekt/app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :galleries
  validates_presence_of :name
end

Projekt/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :gallery
end

Projekt/app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_many :comments
  has_and_belongs_to_many :categories
  validates_presence_of :title, :image

  mount_uploader :image, ImagesUploader
end

Projekt/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

Projekt/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Projekt/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  def cat
    @categories = Category.all
    @galleries = Gallery.all
  end
  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
    @galleries = Gallery.all
  end

  # GET /categories/1/edit
  def edit
    @galleries = Gallery.all
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :gallery_ids => [])
    end
end

Projekt/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @gallery = Gallery.find(params[:gallery_id])
    @comment = @gallery.comments.create(params[:comment].permit(:name,:text))

    redirect_to gallery_path(@gallery)
  end

  def destroy
    @gallery = Gallery.find(params[:gallery_id])
    @comment = @gallery.comments.find(params[:id])
    @comment.destroy

    redirect_to gallery_path(@gallery)
  end
end

Projekt/app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_gallery, only: [:show, :edit, :update, :destroy]

  def gal
    @galleries = Gallery.all
  end

  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
  end

  # GET /galleries/new
  def new
    @gallery = Gallery.new
    @categories = Category.all
  end

  # GET /galleries/1/edit
  def edit
    @categories = Category.all
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
        format.json { render :show, status: :created, location: @gallery }
      else
        format.html { render :new }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galleries/1
  # PATCH/PUT /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { render :show, status: :ok, location: @gallery }
      else
        format.html { render :edit }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to galleries_url, notice: 'Gallery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_params
      params.require(:gallery).permit(:title, :image, :description, :category_ids => [])
    end
end

Projekt/app/helpers/application_helper.rb
module ApplicationHelper
end

Projekt/app/helpers/categories_helper.rb
module CategoriesHelper
end

Projekt/app/helpers/comments_helper.rb
module CommentsHelper
end

Projekt/app/helpers/galleries_helper.rb
module GalleriesHelper
end

Projekt/app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Link the category with posts:" %> <br \>
    <%= collection_check_boxes(:category, :gallery_ids, @galleries, :id, :title) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Projekt/app/views/categories/cat.html.erb
<p id="notice"><%= notice %></p>
<div class="image-responsive" >
<% @categories.each do |category| %>
<h2> <%= category.name %> </h2>
  <% category.galleries.map.each do |g| %>
  <a href=" <%= gallery_url(g) %>"><%= image_tag(g.image.tiny.url) %></a>
  <% end %>
<% end %>
</div>

Projekt/app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

Projekt/app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>
<% if user_signed_in? %>
  <%= link_to 'Create a new Category', new_category_path %>
  <br \> <br \>
<% else %>
  <p> Login to create your own galleries </p>
<% end %>
<% @categories.each do |category| %>
<p>
  <%= category.name %>  
  <p>Linked galleries: <%= category.galleries.map {|g| g.title}.join(', ') %></p>
  <%= link_to 'Show', category %>
  <%= link_to 'Edit', edit_category_path(category) %>
  <%= link_to 'Delete', category, method: :delete, data: { confirm: 'Are you sure?' } %>
</p>
<% end %>

Projekt/app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

Projekt/app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>
<p>
  Linked Galleryposts<br \>
  <%= @category.galleries.map {|g| g.title}.join(', ') %>
</p>
<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

Projekt/app/views/comments/_comment.html.erb
<div class="comment clearfix">
	<div class="comment_content">
		<p class="comment_name"><strong><%= comment.name %></strong></p>
		<p class="comment_text"><%= comment.text %></p>
	</div>

	<% if user_signed_in? %>
	<p><%= link_to 'Delete', [comment.gallery, comment],
								  method: :delete,
								  class: "button",
								 	data: { confirm: 'Are you sure?' } %></p>
 	<% end %>
</div>

Projekt/app/views/comments/_form.html.erb
<%= form_for([@gallery, @gallery.comments.build]) do |f| %>
	<%= f.label :name %><br>
	<%= f.text_field :name %><br>
	<br>
	<%= f.label :text %><br>
	<%= f.text_area :text %><br>
	<br>
	<%= f.submit %>
<% end %>

Projekt/app/views/galleries/_form.html.erb
<%= form_for(@gallery) do |f| %>
  <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% @gallery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
      <%= f.label "Choose categories" %> <br \>
      <%= collection_check_boxes(:gallery, :category_ids, @categories, :id, :name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Projekt/app/views/galleries/edit.html.erb
<h1>Editing Gallery</h1>

<%= render 'form' %>

<%= link_to 'Show', @gallery %> |
<%= link_to 'Back', galleries_path %>

Projekt/app/views/galleries/gal.html.erb
<p id="notice"><%= notice %></p>
<div class="image-responsive" >
<% @galleries.each do |gallery| %>
    <a href=" <%= gallery_url(gallery) %>"><%= image_tag(gallery.image.tiny.url) %></a>
<% end %>
</div>

Projekt/app/views/galleries/index.html.erb
<p id="notice"><%= notice %></p>
<% if user_signed_in? %>
<%= link_to 'Create a new Gallery post', new_gallery_path %>
<% else %>
<p> Login to create your own galleries </p>
<% end %>
<% @galleries.each do |gallery| %>

    <h2><%= gallery.title %></h2>
    <a href=" <%= gallery_url(gallery) %>"><%= image_tag(gallery.image.tiny.url) %></a>
    <p><%= gallery.description %></p>
    <p>Categories: <%= gallery.categories.map {|c| c.name}.join(', ') %></p>

    <% if user_signed_in? %>
      <%= link_to 'Show', gallery %>
      <%= link_to 'Edit', edit_gallery_path(gallery) %>
      <%= link_to 'Delete', gallery, method: :delete, data: { confirm: 'Are you sure?' } %>
      <hr \>
    <% else %>
    <% end %>
<% end %>
<br \>

Projekt/app/views/galleries/new.html.erb
<h2>New Gallery post</h2>

<%= render 'form' %>

<%= link_to 'Back', galleries_path %>

Projekt/app/views/galleries/show.html.erb
<p id="notice"><%= notice %></p>

<% if !user_signed_in? %>
<p> Login to create your own galleries </p>
<% end %>

<p>
  <strong>Title:</strong>
  <%= @gallery.title %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@gallery.image.big.url) %>
</p>

<p>
  <strong>Description:</strong>
  <%= @gallery.description %>
</p>
<p>
  <h3>Linked categories</h3>
  <%= @gallery.categories.map {|c| c.name}.join(', ') %>
</p>
<div id="comments">
  <h2><%= @gallery.comments.count %> Comments</h2>
  <%= render @gallery.comments %>
  <h2> Write a Comment!</h2>
  <%= render "comments/form" %>
</div>
<%= link_to 'Edit', edit_gallery_path(@gallery) %> |
<%= link_to 'Back', galleries_path %>

Projekt/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%=link_to "Home", root_path, class: "navbar-brand"%>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <% if user_signed_in? %>
                <li><%= link_to "Create a post", new_gallery_path %></li>
                <li><%= link_to "Create a category", new_category_path %></li>
                <li><%= link_to "Categories", categories_path %></li>
                <li><%= link_to "Uploads", galleries_gal_path %></li>
                <li><%= link_to "Uploads by Category", categories_cat_path %></li>
                <% end %>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "Login", new_user_session_path %></li>
                <li><%= link_to "Register", new_user_registration_path %></li>
              <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

Projekt/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Projekt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="text-center">
<%= render 'layouts/navbar' %>
<p class="alerts"><%= alert %></p>
<%= yield %>

</body>
<footer class="footer">
  <br \>
  <p> Created by Dominik Richter 2016</p>
</footer>
</html>